    # print verhaal 1
    input('Congratulations, you won!')
    input('You are now on the last floor.')
    input('This floor is a lot like the second, beautifull plains but instead of a sunny, a cloudy sky.')
    input('This floor is a lot easier to navigate than the former jungle one, so you find this guild pretty easily.')
    input('The guild is called The Black Knights, with its well known leader called Lelouch.')
    input('You have heard that Lelouch is quite hard to find, so you try your luck at the guild.')
    input('Fortunatly, people have heard of you, because of your quick progression on the floors.')
    input('Therefore, Lelouch notices you walking inside his guild and meets you in the guild hall.')
    input('Lelouch greets you, you greet him back and ask him about this floors dungeon.')
    input('Lelouch reveals that this boss is a hybrid from a demon and human, a Demonoid to be exact.')
    input('The name of the Demonoid is Zeldris, and is known for overall very high stats.')
    input('Lelouch notices your armor, and says that the armor that you are wearing currently, will not be strong enough.')
    input('Lelouch offers you the newest of new armor, he calls it Incursio, which boosts your HP by 150.')
    input('You are greatfull for his help, so you thank him, and say goodbye te Lelouch')
    input('Lelouch wishes you the best of luck, and you make your way to the last dungeon.')
    input('You walk to the last dungeon entrance. The entrance is a huge door made of gold. You cant help but take a long look at it.')
    input('As you wander around the dungeon looking for the Demonoid called Zeldris that Lelouch spoke of...')
    input('You encounter the Final Boss Zeldris! Prepare to fight!')


    # Verhaallijn 2 
    input('Welcome to the second floor, on this floor you will find another dungeon with new monsters.')
    input('You see a road on decide to walk down the road until see an adventurers guild.')
    input('You walk in and meet the guild leader called Kelvin.')
    input('You ask him about this dungeon and the monsters on this dungeon and what kind of species they are.')
    input('He tells you they are called ghouls, and what they can do.')
    input('Kelvin says that they are like humans, but they eat flesh from humans.')
    input('Kelvin offers you a place for tonight.')
    input('You accept, and go to your room and take some well deserved rest.')
    input('You wake up see Kelvin, and tell him you are going to this floors dungeon.')
    input('Kelvin wishes you luck, and you leave the guild, and you are on your way to the dungeon.')
    input('As you wander around the dungeon looking for the Ghouls that Kelvin spoke of.')
    input('You encounter a Ghoul! Prepare to attack!')