Naam = input("Hoe heet jij?")
Adres = input("Wat is jouw adres")
Postcode = input("Wat is je postcode")
Woonplaats = input('Wat is jouw woonplaats')
print('----------------------------------------------------')
print(f"{Naam}")
print(f"{Adres}")
print(f'{Postcode}')
print(f'{Woonplaats}')
print('----------------------------------------------------')